# Generated by Django 5.0.6 on 2024-06-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_is_ended_auction_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default=0, upload_to='auction_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('bidder', 'Bidder'), ('admin', 'Admin')], max_length=10),
        ),
    ]
