# Generated by Django 5.0.6 on 2024-06-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_auction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('auction_id', models.IntegerField()),
            ],
        ),
    ]
