# Generated by Django 5.0.6 on 2024-06-26 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_taskexecution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auctions', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='duration_minutes',
            field=models.IntegerField(verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(editable=False, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.fish', verbose_name='Fish'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fish_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='Is Ended'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='size_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Size (cm)'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Starting Bid'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction', verbose_name='Auction'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bid Time'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Bidder'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='auction_id',
            field=models.IntegerField(verbose_name='Auction ID'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='execution_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Execution Time'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='task_name',
            field=models.CharField(max_length=255, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('bidder', 'Bidder'), ('admin', 'Admin')], max_length=10, verbose_name='User Type'),
        ),
    ]
